# Overview

Title of project:
Examination of United States Cancer Mortality from 1999-2017 and trends between Race, Ethnicity, Age Group, etc.
Examining Cancer Mortality Through a Variety of Categorical Variables

Name of project author(s):
Brent Cameron

Name of project reviewer:
Zhihan Xian


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

A general description is given, but it is a little bit short. The author could briefly talk about some literature or related work done. He briefly discusses the significance of his study but he could be more clear about what new information he hopes to provide.

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* some contextualization and motivation



## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

The question is pretty straightforward and it is clear the questions relate to the data well.

### Summary assessment

* question/hypotheses somewhat explained



## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

The source of the data is provided and the dataset is briefly described. 

### Summary assessment

* source and overall structure of data somewhat explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

This part is missing.

### Summary assessment
* major weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

Analysis part is yet to finish upon this time.

### Summary assessment
* wrong/inadequate analysis


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The result part is yet to finish upon this time.

### Summary assessment
* results not finished yet


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

The Discussion/Conclusions part is yet to finish upon this time.

### Summary assessment
* major parts of discussion missing or wrong 


## Further comments

_Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project._



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

The project cannot be reviewed at this time yet. Some junk files found in "products" folder. There should be better readme files explaining this project.

### Summary assessment
* the project has major parts missing.


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

The project so far contains very little information. The author has not provided analysis information yet.

### Summary assessment
* not finished



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

NA at this point


### Summary assessment
* NA


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

NA at this point

### Summary assessment
* NA at this point


## Further comments

_Add any other comments regarding the overall project here. Write anything you think can help your classmate improve their project._





